# Generated by Django 4.1.3 on 2024-02-11 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebTabs', '0002_rename_form_formdataform_delete_field'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormDataForm',
            new_name='Form',
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field_type', models.CharField(max_length=100)),
                ('required', models.BooleanField(default=False)),
                ('readable', models.BooleanField(default=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='WebTabs.form')),
            ],
        ),
    ]
