# Generated by Django 4.1.3 on 2024-02-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebTabs', '0006_formdata_delete_formdataentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='checkbox_readable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formdata',
            name='checkbox_required',
            field=models.BooleanField(default=False),
        ),
    ]
