# Generated by Django 4.1.3 on 2024-02-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebTabs', '0008_alter_formdata_checkbox_readable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='checkbox_readable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='checkbox_required',
            field=models.BooleanField(default=False),
        ),
    ]
