# Generated by Django 4.1.3 on 2024-02-13 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebTabs', '0009_alter_formdata_checkbox_readable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formdata',
            name='checkbox_readable',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='checkbox_required',
        ),
    ]
