# Generated by Django 4.1.3 on 2024-02-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebTabs', '0010_remove_formdata_checkbox_readable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=100)),
                ('field_name', models.CharField(max_length=100)),
                ('is_required', models.BooleanField(default=False)),
                ('is_readable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FieldName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=100)),
                ('field_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SelectionBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=100)),
                ('field_name', models.CharField(max_length=100)),
                ('selection_option', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='FormData',
        ),
    ]
