# Generated by Django 4.1.3 on 2024-02-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebTabs', '0012_formdata_delete_checkbox_delete_fieldname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text_input', 'Text Input'), ('select_box', 'Select Box'), ('checkbox', 'Checkbox')], max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='FormData',
        ),
    ]
