# Generated by Django 4.1.3 on 2024-02-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebTabs', '0013_formfield_delete_formdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=100)),
                ('field_name', models.CharField(max_length=100)),
                ('field_value', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='FormField',
        ),
    ]
