# Generated by Django 4.1.3 on 2024-02-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebTabs', '0014_formdata_delete_formfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormDataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_inputs', models.JSONField()),
                ('select_boxes', models.JSONField()),
                ('checkboxes', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FormData',
        ),
    ]
