# Generated by Django 4.1.3 on 2024-02-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebTabs', '0017_rename_form_keys_fielddata_field_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fielddata',
            name='readable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fielddata',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
