# Generated by Django 4.1.3 on 2024-02-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebTabs', '0018_fielddata_readable_fielddata_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckBoxData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(default='empty', max_length=100)),
                ('required', models.BooleanField(default=False)),
                ('readable', models.BooleanField(default=False)),
            ],
        ),
    ]
