# Generated by Django 4.1.3 on 2024-02-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebTabs', '0020_rename_field_key_checkboxdata_readable_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkboxdata',
            old_name='readable_key',
            new_name='field_key',
        ),
        migrations.RemoveField(
            model_name='checkboxdata',
            name='readable_value',
        ),
        migrations.RemoveField(
            model_name='checkboxdata',
            name='required_key',
        ),
        migrations.AddField(
            model_name='checkboxdata',
            name='field_value',
            field=models.CharField(default='value', max_length=255),
        ),
    ]
