# Generated by Django 4.1.3 on 2024-02-16 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebTabs', '0021_rename_readable_key_checkboxdata_field_key_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CheckBoxData',
            new_name='CheckData',
        ),
    ]
