# Generated by Django 4.1.3 on 2024-02-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebTabs', '0022_rename_checkboxdata_checkdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkdata',
            old_name='required_value',
            new_name='readable',
        ),
        migrations.RemoveField(
            model_name='checkdata',
            name='field_key',
        ),
        migrations.RemoveField(
            model_name='checkdata',
            name='field_value',
        ),
        migrations.AddField(
            model_name='checkdata',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
