# Generated by Django 4.1.3 on 2024-02-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebTabs', '0023_rename_required_value_checkdata_readable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkdata',
            name='field_key',
            field=models.CharField(default='empty', max_length=100),
        ),
        migrations.AddField(
            model_name='checkdata',
            name='field_value',
            field=models.CharField(default='value', max_length=255),
        ),
        migrations.AddField(
            model_name='checkdata',
            name='selection_value',
            field=models.CharField(default='value', max_length=100),
        ),
    ]
