# Generated by Django 4.1.3 on 2024-02-16 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebTabs', '0024_checkdata_field_key_checkdata_field_value_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckData',
        ),
    ]
