# Generated by Django 4.2.5 on 2024-02-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebTabs', '0025_delete_checkdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fielddata',
            name='readable',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='required',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
